### ISSUE TITLE
Preserving Source IP addresses

### ISSUE THREAD

**Issue by slabber** [Azure/ACS#8]
I have exposed an nginx container using:
```
kubectl run my-nginx --image=nginx --port 80
kubectl expose deployment my-nginx --port=80 --type=LoadBalancer --session-affinity=ClientIP
```

But when I look at the Source IP addresses in the nginx logs I still see the IP address of the cluster.

The docs [here](https://github.com/Azure/ACS/blob/master/kubernetes-status.md) state that Source IP preservation on L4 load balancers should be implemented but it's not clear how.  As far as I can see my traffic is still being SNAT'd on the kubernetes node.

Is this the desired behaviour?

In order to have the correct source IPs do I have to wait until the Ingress Controller is working via Application Gateways and then examine some header for the original source?

Tx

**Comment by colemickens** [comment]
Please see this documentation: https://kubernetes.io/docs/tutorials/services/source-ip/

You need to use an annotation on the Service to opt-in to source IP preservation. You'll want to put that annotation on when creating as well, rather than adding it later as the tutorial says, as the Azure code is buggy and doesn't update the loadbalancer for certain annotations.
