### ISSUE TITLE
Kubernetes Deployments are Flakey

### ISSUE THREAD

**Issue by colemickens** [Azure/ACS#9]
This can manifest itself in a couple ways:

1. The cluster is not healthy and the user is unable to issue `kubectl` commands, even from the master nodes.

2. The user is unable to retrieve credentials using the cli (aka `az acs get-credentials` or `az acs kubernetes get-credentials` fails)

The issue stems from instability in an external dependency: hkp://ha.pool.sks-keyservers.net:80 

We are currently hot fixing to mitigate this issue and building remediation instructions for broken clusters.

**Comment by colemickens** [comment]
To be more specific, you can see two different behaviors, depending on what type of Kubernetes cluster:

1. You choose Linux agents. The Azure deployment will report success, but the control plane may not be reachable, and the `az acs get-crendentials` may not work.

2. You choose Windows agents. The Azure deployment will time out after 90 minutes due to customScriptExtension failing on one or more of the Windows nodes.

**Comment by brendandburns** [comment]
Here is a temporary work-around that I believe will fix broken nodes/masters:

On each machine:

```sh
for ! sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D; do
  sleep 1
done

sudo rm -rf /var/lib/cloud/instances
sudo cloud-init -d init
sudo cloud-init -d modules -m config
sudo cloud-init -d modules -m final
sudo systemctl status kubelet
```

**Comment by JonathanFraser** [comment]
With regards to the key server, the issue is likely the insistence on using port 80 instead of the default port. Apparently the port 80 servers have a much lower availability.
```
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

**Comment by colemickens** [comment]
Thanks @JonathanFraser. The solution we're pursuing now more closely aligns with what Docker recommends: `curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -` (https://docs.docker.com/engine/installation/linux/ubuntu/). Longer term we will have Azure-hosted mirrors for these things so we're not affected by other things such as S3 going down...

**Comment by brendandburns** [comment]
Verified that the workaround above fixes broken nodes, here's the script to run:

```sh
#!/bin/bash

while ! sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D; do
  echo 'Failed to load keys'
  sleep 1
done

sudo rm -rf /var/lib/cloud/instances
sudo cloud-init -d init
sudo cloud-init -d modules -m config
sudo cloud-init -d modules -m final
sudo systemctl restart kubelet
```

**Comment by brendandburns** [comment]
A few more instructions...

If you are restoring a master node, not an agent node, you need to do the following (slightly more complicated)

```sh
#!/bin/bash

sudo systemctl stop etcd
sudo rm -rf /var/lib/etcd/default
sudo perl -pi -e "s/initial-cluster-state new/initial-cluster-state existing/g" /etc/default/etcd
sudo systemctl restart etcd
sudo systemctl restart docker
sudo systemctl restart kubelet
```

**Comment by mfaizanse** [comment]
@brendandburns Any solution if the CSE is failing on windows nodes?

**Comment by colemickens** [comment]
The failing on Windows nodes is caused by this process failing on master. For now, you need to wait for a mitigation or keep redeploying until you get one where the master comes up.

**Comment by mfaizanse** [comment]
![capture](https://cloud.githubusercontent.com/assets/9897945/23502812/f47b5d54-ff5a-11e6-895a-5da5e3e6057c.PNG)

I think the master is up but the agents are in Running status.

**Comment by colemickens** [comment]
The node running doesn't mean provisioning succeeded. This problem is specifically caused by a (flakey) failure at provisioning time.

**Comment by mfaizanse** [comment]
How much time the CSE takes to complete successfully?

**Comment by brendanacassidy** [comment]
I ran the workarounds (with the revised master-specific workaround), first on the workers, which executed without error, and then on the master, which returned a non-zero error:

`Job for etcd.service failed because the control process exited with error code. See "systemctl status etcd.service" and "journalctl -xe" for details.
`

Investing further yielded:

`gf@k8s-master-1488478457-0:~/.ssh$ systemctl status etcd.service
● etcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-03-02 18:50:07 UTC; 1min 10s ago
     Docs: https://github.com/coreos/etcd
           man:etcd
  Process: 25633 ExecStart=/usr/bin/etcd $DAEMON_ARGS (code=exited, status=1/FAILURE)
 Main PID: 25633 (code=exited, status=1/FAILURE)

Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: Starting etcd - highly-available key value store...
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd/default
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: etcd Version: 2.2.5
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: Failed to start etcd - highly-available key value store.
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Unit entered failed state.
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Failed with result 'exit-code'.
lines 1-16/16 (END)...skipping...
● etcd.service - etcd - highly-available key value store                                                                                                                                                                                                                       
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)                                                                                                                                                                                          
   Active: failed (Result: exit-code) since Thu 2017-03-02 18:50:07 UTC; 1min 10s ago                                                                                                                                                                                          
     Docs: https://github.com/coreos/etcd                                                                                                                                                                                                                                      
           man:etcd                                                                                                                                                                                                                                                            
  Process: 25633 ExecStart=/usr/bin/etcd $DAEMON_ARGS (code=exited, status=1/FAILURE)                                                                                                                                                                                          
 Main PID: 25633 (code=exited, status=1/FAILURE)                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: Starting etcd - highly-available key value store...                                                                                                                                                                        
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd/default                                                                                                                                              
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag                                                                                                                                     
Mar 02 18:50:07 k8s-master-1488478457-0 etcd[25633]: etcd Version: 2.2.5                                                                                                                                                                                                       
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE                                                                                                                                                           
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: Failed to start etcd - highly-available key value store.                                                                                                                                                                   
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Unit entered failed state.                                                                                                                                                                                   
Mar 02 18:50:07 k8s-master-1488478457-0 systemd[1]: etcd.service: Failed with result 'exit-code'.`

and

`gf@k8s-master-1488478457-0:~/.ssh$ journalctl -xe
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: I0302 18:51:01.207829   26137 feature_gate.go:189] feature gates: map[]
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: Error: failed to run Kubelet: could not init cloud provider "azure": autorest/azure: There is no cloud environment matching the name "LS0TLS1CRUDJTIBSU0EGUFJJVKFURSBLRVKTLS0TLQPNSULKS2DJQKFBS0NBZ0VBN0LRCYTMRKOVSK5FQ1
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: JRNFBNRMHDBGNHQVVDZ2DFQKFPNWNVSU9XCM9MCEV2WLZYEMFKAM1IQTLSU1VDBFV1ENVRB25COGLJUUF5NZFOQ0RKVW8WZHLSDMFXEFC5WKHUMEDBY1PZAKUKZUFKNGVOWHHKSJNRV1FXK2WRSFPXMLRBBEDDTU5UBYTYVFNBWGFYNDQZBDJQUFFJUZFQELPKSHNQU0TKWFLVAQP3VG80WT
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: 5NMGQYNLRFMZFUYXBXZ3CWVM03NURZSXMRVXMRRHZ0VDNGQ0PITU8VWFOXAU1BVJBPCJE1WWDQU2ZKNLVBTI9ZV3HLRMVXZ243BDDQVMNRRKTMQMZ2K3NVNGPVMFM5D3ZVBYTBK3JOUE44S3URDW5AWWQKV1RQR0FTRHNQZE5YRHVKEUHRDLRHD0ZZBITUVFJ1TNZLTZJDEENQTMOXRLPDCT
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: failed to run Kubelet: could not init cloud provider "azure": autorest/azure: There is no cloud environment matching the name "LS0TLS1CRUDJTIBSU0EGUFJJVKFURSBLRVKTLS0TLQPNSULKS2DJQKFBS0NBZ0VBN0LRCYTMRKOVSK5FQ1FTL29SL
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: MHDBGNHQVVDZ2DFQKFPNWNVSU9XCM9MCEV2WLZYEMFKAM1IQTLSU1VDBFV1ENVRB25COGLJUUF5NZFOQ0RKVW8WZHLSDMFXEFC5WKHUMEDBY1PZAKUKZUFKNGVOWHHKSJNRV1FXK2WRSFPXMLRBBEDDTU5UBYTYVFNBWGFYNDQZBDJQUFFJUZFQELPKSHNQU0TKWFLVAQP3VG80WTKWVM5XT
Mar 02 18:51:01 k8s-master-1488478457-0 docker[26113]: LRFMZFUYXBXZ3CWVM03NURZSXMRVXMRRHZ0VDNGQ0PITU8VWFOXAU1BVJBPCJE1WWDQU2ZKNLVBTI9ZV3HLRMVXZ243BDDQVMNRRKTMQMZ2K3NVNGPVMFM5D3ZVBYTBK3JOUE44S3URDW5AWWQKV1RQR0FTRHNQZE5YRHVKEUHRDLRHD0ZZBITUVFJ1TNZLTZJDEENQTMOXRLPDCTBKAVLAW
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 18:51:17 k8s-master-1488478457-0 docker[25648]: time="2017-03-02T18:51:17.810832692Z" level=error msg="Handler for POST /v1.24/containers/kubelet/stop returned error: Container kubelet is already stopped"
Mar 02 18:51:17 k8s-master-1488478457-0 docker[26163]: kubelet
Mar 02 18:51:17 k8s-master-1488478457-0 docker[26172]: kubelet
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: kubelet.service: Unit entered failed state.
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: Stopped Kubelet.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
Mar 02 18:51:17 k8s-master-1488478457-0 systemd[1]: Starting Kubelet...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.
Mar 02 18:51:37 k8s-master-1488478457-0 systemd[1]: Started Kubelet.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: I0302 18:51:43.159581   26248 feature_gate.go:189] feature gates: map[]
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: Error: failed to run Kubelet: could not init cloud provider "azure": autorest/azure: There is no cloud environment matching the name "LS0TLS1CRUDJTIBSU0EGUFJJVKFURSBLRVKTLS0TLQPNSULKS2DJQKFBS0NBZ0VBN0LRCYTMRKOVSK5FQ1
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: JRNFBNRMHDBGNHQVVDZ2DFQKFPNWNVSU9XCM9MCEV2WLZYEMFKAM1IQTLSU1VDBFV1ENVRB25COGLJUUF5NZFOQ0RKVW8WZHLSDMFXEFC5WKHUMEDBY1PZAKUKZUFKNGVOWHHKSJNRV1FXK2WRSFPXMLRBBEDDTU5UBYTYVFNBWGFYNDQZBDJQUFFJUZFQELPKSHNQU0TKWFLVAQP3VG80WT
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: 5NMGQYNLRFMZFUYXBXZ3CWVM03NURZSXMRVXMRRHZ0VDNGQ0PITU8VWFOXAU1BVJBPCJE1WWDQU2ZKNLVBTI9ZV3HLRMVXZ243BDDQVMNRRKTMQMZ2K3NVNGPVMFM5D3ZVBYTBK3JOUE44S3URDW5AWWQKV1RQR0FTRHNQZE5YRHVKEUHRDLRHD0ZZBITUVFJ1TNZLTZJDEENQTMOXRLPDCT
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: failed to run Kubelet: could not init cloud provider "azure": autorest/azure: There is no cloud environment matching the name "LS0TLS1CRUDJTIBSU0EGUFJJVKFURSBLRVKTLS0TLQPNSULKS2DJQKFBS0NBZ0VBN0LRCYTMRKOVSK5FQ1FTL29SL
Mar 02 18:51:43 k8s-master-1488478457-0 docker[26223]: MHDBGNHQVVDZ2DFQKFPNWNVSU9XCM9MCEV2WLZYEMFKAM1IQTLSU1VDBFV1ENVRB25COGLJUUF5NZFOQ0RKVW8WZHLSDMFXEFC5WKHUMEDBY1PZAKUKZUFKNGVOWHHKSJNRV1FXK2WRSFPXMLRBBEDDTU5UBYTYVFNBWGFYNDQZBDJQUFFJUZFQELPKSHNQU0TKWFLVAQP3VG80WTKWVM5XT
Mar 02 18:51:44 k8s-master-1488478457-0 docker[26223]: LRFMZFUYXBXZ3CWVM03NURZSXMRVXMRRHZ0VDNGQ0PITU8VWFOXAU1BVJBPCJE1WWDQU2ZKNLVBTI9ZV3HLRMVXZ243BDDQVMNRRKTMQMZ2K3NVNGPVMFM5D3ZVBYTBK3JOUE44S3URDW5AWWQKV1RQR0FTRHNQZE5YRHVKEUHRDLRHD0ZZBITUVFJ1TNZLTZJDEENQTMOXRLPDCTBKAVLAW
Mar 02 18:52:16 k8s-master-1488478457-0 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 18:52:16 k8s-master-1488478457-0 docker[25648]: time="2017-03-02T18:52:16.902588291Z" level=error msg="Handler for POST /v1.24/containers/kubelet/stop returned error: Container kubelet is already stopped"
Mar 02 18:52:16 k8s-master-1488478457-0 docker[26276]: kubelet
Mar 02 18:52:16 k8s-master-1488478457-0 docker[26286]: kubelet
Mar 02 18:52:16 k8s-master-1488478457-0 systemd[1]: kubelet.service: Unit entered failed state.
Mar 02 18:52:16 k8s-master-1488478457-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 02 18:52:17 k8s-master-1488478457-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar 02 18:52:17 k8s-master-1488478457-0 systemd[1]: Stopped Kubelet.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
Mar 02 18:52:17 k8s-master-1488478457-0 systemd[1]: Starting Kubelet...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.`

**Comment by colemickens** [comment]
Shouldn't be more than 10 minutes. Can we please hold off on troubleshooting win+k8s on ACS until the service is back to reliable? I'm happy to help you debug ACS-Engine sooner in the other issue. Thanks.

**Comment by colemickens** [comment]
@brendanacassidy That sounds like a cluster deployed with ACS-Engine, please keep those issues in the ACS-Engine repository. Additionally, that bug has already been fixed.

**Comment by colemickens** [comment]
The fix was finished rolling globally at 11:42AM Pacific time. This is now resolved.
